# Generated by Django 5.1.7 on 2025-05-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_alter_func_registrar_produto_imagem_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='func_registrar_produto',
            name='tipo_direito',
            field=models.CharField(choices=[('compartilhado', 'Direito Compartilhado'), ('pleno', 'Direito Pleno')], default='compartilhado', max_length=20),
        ),
        migrations.AddField(
            model_name='func_registrar_produto',
            name='vendido',
            field=models.BooleanField(default=False),
        ),
    ]
